azure:
  user_or_org: cctbx-release
  project_name: feedstock-builds
  store_build_artifacts: true
build_platform:
  osx_arm64: osx_64
conda_build:
  pkg_format: '2'
  zstd_compression_level: 22
github:
  user_or_org: cci-lbl
  repo_name: dssp-feedstock
  branch_name: main
  tooling_branch_name: main
test: native
upload_on_branch: upload
